# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jenova.network.proto import jenova_pb2 as jenova__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jenova_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JenovaRPCStub(object):
    """Service definition for distributed JENOVA operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateText = channel.unary_unary(
                '/jenova.JenovaRPC/GenerateText',
                request_serializer=jenova__pb2.GenerateRequest.SerializeToString,
                response_deserializer=jenova__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GenerateTextStream = channel.unary_stream(
                '/jenova.JenovaRPC/GenerateTextStream',
                request_serializer=jenova__pb2.GenerateRequest.SerializeToString,
                response_deserializer=jenova__pb2.GenerateStreamResponse.FromString,
                _registered_method=True)
        self.EmbedText = channel.unary_unary(
                '/jenova.JenovaRPC/EmbedText',
                request_serializer=jenova__pb2.EmbedRequest.SerializeToString,
                response_deserializer=jenova__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.EmbedTextBatch = channel.unary_unary(
                '/jenova.JenovaRPC/EmbedTextBatch',
                request_serializer=jenova__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=jenova__pb2.EmbedBatchResponse.FromString,
                _registered_method=True)
        self.SearchMemory = channel.unary_unary(
                '/jenova.JenovaRPC/SearchMemory',
                request_serializer=jenova__pb2.MemorySearchRequest.SerializeToString,
                response_deserializer=jenova__pb2.MemorySearchResponse.FromString,
                _registered_method=True)
        self.SearchMemoryFederated = channel.unary_unary(
                '/jenova.JenovaRPC/SearchMemoryFederated',
                request_serializer=jenova__pb2.MemorySearchRequest.SerializeToString,
                response_deserializer=jenova__pb2.MemorySearchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/jenova.JenovaRPC/HealthCheck',
                request_serializer=jenova__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=jenova__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/jenova.JenovaRPC/GetCapabilities',
                request_serializer=jenova__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=jenova__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/jenova.JenovaRPC/GetMetrics',
                request_serializer=jenova__pb2.MetricsRequest.SerializeToString,
                response_deserializer=jenova__pb2.MetricsResponse.FromString,
                _registered_method=True)


class JenovaRPCServicer(object):
    """Service definition for distributed JENOVA operations
    """

    def GenerateText(self, request, context):
        """LLM inference operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTextStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedText(self, request, context):
        """Embedding operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedTextBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemory(self, request, context):
        """Memory operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemoryFederated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health and status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JenovaRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=jenova__pb2.GenerateRequest.FromString,
                    response_serializer=jenova__pb2.GenerateResponse.SerializeToString,
            ),
            'GenerateTextStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateTextStream,
                    request_deserializer=jenova__pb2.GenerateRequest.FromString,
                    response_serializer=jenova__pb2.GenerateStreamResponse.SerializeToString,
            ),
            'EmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedText,
                    request_deserializer=jenova__pb2.EmbedRequest.FromString,
                    response_serializer=jenova__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedTextBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedTextBatch,
                    request_deserializer=jenova__pb2.EmbedBatchRequest.FromString,
                    response_serializer=jenova__pb2.EmbedBatchResponse.SerializeToString,
            ),
            'SearchMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemory,
                    request_deserializer=jenova__pb2.MemorySearchRequest.FromString,
                    response_serializer=jenova__pb2.MemorySearchResponse.SerializeToString,
            ),
            'SearchMemoryFederated': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemoryFederated,
                    request_deserializer=jenova__pb2.MemorySearchRequest.FromString,
                    response_serializer=jenova__pb2.MemorySearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=jenova__pb2.HealthCheckRequest.FromString,
                    response_serializer=jenova__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=jenova__pb2.CapabilitiesRequest.FromString,
                    response_serializer=jenova__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=jenova__pb2.MetricsRequest.FromString,
                    response_serializer=jenova__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jenova.JenovaRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jenova.JenovaRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JenovaRPC(object):
    """Service definition for distributed JENOVA operations
    """

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jenova.JenovaRPC/GenerateText',
            jenova__pb2.GenerateRequest.SerializeToString,
            jenova__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTextStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jenova.JenovaRPC/GenerateTextStream',
            jenova__pb2.GenerateRequest.SerializeToString,
            jenova__pb2.GenerateStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jenova.JenovaRPC/EmbedText',
            jenova__pb2.EmbedRequest.SerializeToString,
            jenova__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedTextBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jenova.JenovaRPC/EmbedTextBatch',
            jenova__pb2.EmbedBatchRequest.SerializeToString,
            jenova__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jenova.JenovaRPC/SearchMemory',
            jenova__pb2.MemorySearchRequest.SerializeToString,
            jenova__pb2.MemorySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemoryFederated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jenova.JenovaRPC/SearchMemoryFederated',
            jenova__pb2.MemorySearchRequest.SerializeToString,
            jenova__pb2.MemorySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jenova.JenovaRPC/HealthCheck',
            jenova__pb2.HealthCheckRequest.SerializeToString,
            jenova__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jenova.JenovaRPC/GetCapabilities',
            jenova__pb2.CapabilitiesRequest.SerializeToString,
            jenova__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jenova.JenovaRPC/GetMetrics',
            jenova__pb2.MetricsRequest.SerializeToString,
            jenova__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
